DROP TABLE accounts CASCADE CONSTRAINTS;
DROP SEQUENCE id_number;

CREATE SEQUENCE id_number START WITH 1 INCREMENT BY 1;

CREATE TABLE accounts (
    id NUMBER PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    passwd VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL
);