name: Citadel Azure
on:
  push:
    branches:
      - main 
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            echo "Succesfully connected to Azure!"

            # update BETA directory
            if [ "${{ github.ref }}" = "refs/heads/beta" ]; 
            then
              echo "Deploying to BETA..."
              cd ${{ secrets.WEBSITE_BETA_PATH }} \
              && git fetch origin \
              && git reset --hard origin/beta \
              && cd website \
              && npm install \
              && npm run build \
              && echo "[OK] Pull succesfully into BETA directory" \
              || { echo "[ERROR] Pulling into BETA directory failed!"; exit 1; }
            
            # update MAIN directory
            elif [ "${{ github.ref }}" = "refs/heads/main" ];
            then
              echo "Deploying to MAIN..."
              cd ${{ secrets.WEBSITE_PATH }} \
              && git fetch origin \
              && git reset --hard origin/main \
              && cd website \
              && npm install \
              && npm run build \
              && echo "[OK] Pull succesfully into MAIN directory" \
              || { echo "[ERROR] Pulling into MAIN directory failed!"; exit 1; }
            fi

            # nginx
            echo "[NGINX] Reloading..."
            sudo systemctl reload nginx && echo "Deployment successful on Azure!" || { echo "Deployment failed!"; exit 1; }





